### ISSUE TITLE
Unable to add repository (404)

### ISSUE THREAD

**Issue by isamudaison** [pbek/loganalyzer#10]
#### Expected behaviour
Executing `sudo add-apt-repository ppa:pbek/loganalyzer` should successfully add the repo.

#### Actual behaviour
404 error not found:
```
Err:13 http://ppa.launchpad.net/pbek/loganalyzer/ubuntu focal Release                         
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
```
```
E: The repository 'http://ppa.launchpad.net/pbek/loganalyzer/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
#### Steps to reproduce
Execute `sudo add-apt-repository ppa:pbek/loganalyzer`

#### Output from the debug section in the settings dialog
N/A

Output of `uname -a`:
```
Linux ws-isamudaison 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pbek** [comment]
There never was a release for focal on https://launchpad.net/~pbek/+archive/ubuntu/loganalyzer/+packages.

Meanwhile you could try the deb files for bionic or cosmic.

**Comment by pbek** [comment]
I now released builds for up to 21.10 in the PPA. Did they work for you?

**Comment by isamudaison** [comment]
Confirmed; I can add the repository, update it, and install the `loganalyzer` package and run it bare-metal. Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
