### ISSUE TITLE
Im confused about this tool

### ISSUE THREAD

**Issue by mobagenie** [pbek/loganalyzer#11]
i try to explain by myself but still have no idea about this tools.

i try searching some doc but only about feature.

and this need more explanation :

There is an extension for eZ Publish (legacy) to download log files directly from the server.

is this tools related to /var/log file like system.log, boot.log etc?

sorry if ih mistake but i want to monitoring log file in linux  or file log ind /var/log with this tools.

**Comment by pbek** [comment]
Mostly this tool was just about parsing log files for text.

**Comment by pbek** [comment]
Wiping out certain "usual" parts of the the text files so that you can look at the parts that are unusual.

**Comment by mobagenie** [comment]
> Mostly this tool was just about parsing log files for text.

yes that more than i need and that whta i need. i just want to monitoring unknown activities.

my problm is i cant explain how to use this tools

**Comment by pbek** [comment]
You need to write regular expressions for the parts that should be removed from the view until only all the interesting parts are left.

**Comment by mobagenie** [comment]
> Reference



> You need to write regular expressions for the parts that should be removed from the view until only all the interesting parts are left.

ok there my last question. so, baiscly this tool can monitoring /var/log with corect configuration ( filter patern) or not? 

i just doont want to wasting something that not related or imposible to my situation.

**Comment by pbek** [comment]
No, this is no automatic monitoring tool as in "log files get constantly monitored and you'll get a notification when something interesting happens".
