### ISSUE TITLE
How compile on Ubuntu 24.04 ?

### ISSUE THREAD

**Issue by dacorsa** [pbek/loganalyzer#15]
Hi all,

i want to compile latest version of loganalyzer on ubuntu noble 24.04, i run this code:

cd /app
git clone https://github.com/pbek/loganalyzer.git -b develop
cd loganalyzer/
git reset --hard
git pull
git pull --recurse
cd /app/loganalyzer/src/libraries/
git clone https://github.com/pbek/qmarkdowntextedit.git
cd /app/loganalyzer/src/libraries/qmarkdowntextedit/
git reset --hard
git pull
git pull --recurse
git checkout a23cc53
cd /app/loganalyzer/src/
qmake
make

but i receive this error:

`Info: creating stash file /app/loganalyzer/src/.qmake.stash
/home/dacorsa/Qt/6.7.0/gcc_64/libexec/uic mainwindow.ui -o ui_mainwindow.h
/home/dacorsa/Qt/6.7.0/gcc_64/libexec/uic dialogs/settingsdialog.ui -o ui_settingsdialog.h
/home/dacorsa/Qt/6.7.0/gcc_64/libexec/uic libraries/qmarkdowntextedit/qplaintexteditsearchwidget.ui -o ui_qplaintexteditsearchwidget.h
g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQAPPLICATION_CLASS=QApplication -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -I/home/dacorsa/Qt/6.7.0/gcc_64/include -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtSvg -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtPrintSupport -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtSql -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetwork -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore -I. -I. -I/home/dacorsa/Qt/6.7.0/gcc_64/mkspecs/linux-g++ -o main.o main.cpp
g++ -c -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT -DQAPPLICATION_CLASS=QApplication -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -I/home/dacorsa/Qt/6.7.0/gcc_64/include -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtSvg -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtPrintSupport -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtSql -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetwork -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore -I. -I. -I/home/dacorsa/Qt/6.7.0/gcc_64/mkspecs/linux-g++ -o mainwindow.o mainwindow.cpp
mainwindow.cpp: In member function ‘bool MainWindow::removeSelectedIgnorePatterns()’:
mainwindow.cpp:391:60: error: ‘null’ is not a member of ‘QString’
  391 |                     tr("&Remove"), tr("&Cancel"), QString::null,
      |                                                            ^~~~
mainwindow.cpp: In member function ‘bool MainWindow::removeSelectedReportPatterns()’:
mainwindow.cpp:418:60: error: ‘null’ is not a member of ‘QString’
  418 |                     tr("&Remove"), tr("&Cancel"), QString::null,
      |                                                            ^~~~
mainwindow.cpp: In member function ‘bool MainWindow::removeLogFiles()’:
mainwindow.cpp:445:60: error: ‘null’ is not a member of ‘QString’
  445 |                     tr("&Remove"), tr("&Cancel"), QString::null,
      |                                                            ^~~~
mainwindow.cpp: In member function ‘bool MainWindow::removeLocalLogFiles()’:
mainwindow.cpp:482:60: error: ‘null’ is not a member of ‘QString’
  482 |                     tr("&Remove"), tr("&Cancel"), QString::null,
      |                                                            ^~~~
mainwindow.cpp: In member function ‘void MainWindow::findCurrentIgnorePattern()’:
mainwindow.cpp:531:5: error: ‘QRegExp’ was not declared in this scope
  531 |     QRegExp expression(item->text());
      |     ^~~~~~~
mainwindow.cpp:532:28: error: ‘expression’ was not declared in this scope
  532 |     ui->fileTextEdit->find(expression);
      |                            ^~~~~~~~~~
mainwindow.cpp: In member function ‘void MainWindow::findCurrentReportPattern()’:
mainwindow.cpp:550:5: error: ‘QRegExp’ was not declared in this scope
  550 |     QRegExp expression(item->text());
      |     ^~~~~~~
mainwindow.cpp:551:28: error: ‘expression’ was not declared in this scope
  551 |     ui->fileTextEdit->find(expression);
      |                            ^~~~~~~~~~
mainwindow.cpp: In member function ‘void MainWindow::on_removeIgnoredPatternsButton_clicked()’:
mainwindow.cpp:754:29: error: ‘QRegExp’ was not declared in this scope
  754 |     logText = logText.split(QRegExp("\n|\r\n"), QString::SkipEmptyParts)
      |                             ^~~~~~~
mainwindow.cpp:754:58: error: ‘SkipEmptyParts’ is not a member of ‘QString’
  754 |     logText = logText.split(QRegExp("\n|\r\n"), QString::SkipEmptyParts)
      |                                                          ^~~~~~~~~~~~~~
mainwindow.cpp: In member function ‘void MainWindow::on_ignorePatternFilterLineEdit_textChanged(const QString&)’:
mainwindow.cpp:859:19: warning: ‘qsizetype QString::count() const’ is deprecated: Use size() or length() instead. [-Wdeprecated-declarations]
  859 |     if (arg1.count() >= 2) {
      |         ~~~~~~~~~~^~
In file included from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/qobject.h:11,
                 from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets/qwidget.h:9,
                 from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets/qmainwindow.h:8,
                 from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets/QMainWindow:1,
                 from mainwindow.h:4,
                 from mainwindow.cpp:1:
/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/qstring.h:187:22: note: declared here
  187 |     inline qsizetype count() const { return d.size; }
      |                      ^~~~~
mainwindow.cpp: In member function ‘void MainWindow::on_reportPatternFilterLineEdit_textChanged(const QString&)’:
mainwindow.cpp:884:19: warning: ‘qsizetype QString::count() const’ is deprecated: Use size() or length() instead. [-Wdeprecated-declarations]
  884 |     if (arg1.count() >= 2) {
      |         ~~~~~~~~~~^~
/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/qstring.h:187:22: note: declared here
  187 |     inline qsizetype count() const { return d.size; }
      |                      ^~~~~
mainwindow.cpp: In member function ‘void MainWindow::loadLocalLogFileSourceFiles(QString)’:
mainwindow.cpp:1347:52: error: ‘class QDateTime’ has no member named ‘toTime_t’
 1347 |             mtimeItem->setData(Qt::UserRole, mTime.toTime_t());
      |                                                    ^~~~~~~~
mainwindow.cpp: In member function ‘void MainWindow::fillEzPublishRemoteFilesListWidget(QJsonArray)’:
mainwindow.cpp:1469:42: error: ‘fromTime_t’ is not a member of ‘QDateTime’
 1469 |             QDateTime mTime = QDateTime::fromTime_t(fileMTime);
      |                                          ^~~~~~~~~~
mainwindow.cpp: In member function ‘void MainWindow::updateEzPublishRemoteFileDownloadStatus(QString, double)’:
mainwindow.cpp:1537:19: error: ‘class QTableWidgetItem’ has no member named ‘setBackgroundColor’; did you mean ‘setBackground’?
 1537 |             item->setBackgroundColor(backgroundColor);
      |                   ^~~~~~~~~~~~~~~~~~
      |                   setBackground
In file included from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/qglobal.h:57,
                 from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui/qtguiglobal.h:7,
                 from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h:7,
                 from /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets/qmainwindow.h:7:
/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/qforeach.h: In instantiation of ‘QtPrivate::QForeachContainer<typename std::decay<_Tp>::type> QtPrivate::qMakeForeachContainer(T&&) [with T = QJsonArray&; typename std::decay<_Tp>::type = QJsonArray]’:
mainwindow.cpp:1445:5:   required from here
   60 |     for (auto name = QtPrivate::qMakeForeachContainer(container); name.i != name.e; ++name.i) \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/qforeach.h:51:61: warning: ‘void QtPrivate::warnIfContainerIsNotShared(...) [with T = QJsonArray]’ is deprecated: Do not use foreach/Q_FOREACH with containers which are not implicitly shared. Prefer using a range-based for loop with these containers: `for (const auto &it : container)`, keeping in mind that range-based for doesn't copy the container as Q_FOREACH does [-Wdeprecated-declarations]
   51 |     warnIfContainerIsNotShared<typename std::decay<T>::type>(0);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/qforeach.h:45:13: note: declared here
   45 | inline void warnIfContainerIsNotShared(...) {}
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:4252: mainwindow.o] Errore 1`

Can you help me please?

Best regards

**Comment by pbek** [comment]
I haven't tested with the latest version of https://github.com/pbek/qmarkdowntextedit.
And I haven't tested building the app with Qt6 (or did any porting)! Have you tried Qt5?

E.g. `QRegExp` doesn't exist in Qt6, you'd need to add `QT += core5compat` to the project file for Qt6 (or to the qmake command).

**Comment by pbek** [comment]
Btw. I also created a package in the nix store, if you want to install the app with nix, it's called `loganalyzer`. 😉

This is the config: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/loganalyzer/default.nix

**Comment by dacorsa** [comment]
> I haven't tested with the latest version of https://github.com/pbek/qmarkdowntextedit. And I haven't tested building the app with Qt6 (or did any porting)! Have you tried Qt5?
> 
> E.g. `QRegExp` doesn't exist in Qt6, you'd need to add `QT += core5compat` to the project file for Qt6 (or to the qmake command).

ok let me try maybe with:

qmake QT += core5compat

can be?

**Comment by dacorsa** [comment]
no also tested adding this to the line 7 for LogAnalyzer.pro file in src:

QT       += core gui svg sql printsupport network core5compat

not works, can you well explain to me how test your file "default.nix" ??? please

**Comment by pbek** [comment]
> not works

Then you would need to install QT5 and use qmake5.

> can you well explain to me how test your file "default.nix" ??? please

It's already prebuild for nix (see https://search.nixos.org/packages?channel=unstable&show=loganalyzer&from=0&size=50&sort=relevance&type=packages&query=loganalyzer).

On Ubuntu, you'd first need to install nix, the package manager.
E.g. see: https://itsfoss.com/ubuntu-install-nix-package-manager/

**Comment by dacorsa** [comment]
ok thanks for all the info.

**Comment by dacorsa** [comment]
OK worked also the compilation:

cd /app
git clone https://github.com/pbek/loganalyzer.git -b develop
cd loganalyzer/
git reset --hard
git pull
git pull --recurse
cd /app/loganalyzer/src/libraries/
git clone https://github.com/pbek/qmarkdowntextedit.git
cd /app/loganalyzer/src/libraries/qmarkdowntextedit/
git reset --hard
git pull
git pull --recurse
git checkout a23cc53
cd /app/loganalyzer/src/
export PATH=/usr/lib/qt5/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/qt5:$LD_LIBRARY_PATH
qmake
make
ls -la /app/loganalyzer/src/LogAnalyzer
exit

![immagine](https://github.com/pbek/loganalyzer/assets/36949692/e63b8d8c-ac26-4870-8aec-d84a188a2da9)

Thanks, bye

**Comment by pbek** [comment]
Great it worked!

Just as a side-note, you don't need to check out the submodules by hand, you just do a `git clone https://github.com/pbek/loganalyzer.git -b develop --recurse-submodules`, it will check out the correct commits of the submodules.

**Comment by dacorsa** [comment]
Thanks Patrizio,

ciao a presto !

**Comment by dacorsa** [comment]
Thanks Patrizio:

sudo killall -9 LogAnalyzer
cd /app
git clone https://github.com/pbek/loganalyzer.git -b develop --recurse-submodules
cd loganalyzer/
git reset --hard
git pull
cd /app/loganalyzer/src/
export PATH=/usr/lib/qt5/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/qt5:$LD_LIBRARY_PATH
qmake
make -j$(proc)
sudo make install
ls -la /app/loganalyzer/src/LogAnalyzer
exit

ciao a presto
