### ISSUE TITLE
cursor jumps to beginning of file when coming back to loganalyzer

### ISSUE THREAD

**Issue by ghost** [pbek/loganalyzer#7]
when we move away to another screen (does not matter if we use alt+tab or clicking or if the other screen is full screen or not), When we come back to loganalyzer, the cursor jumps to the beginning of the log.

If you need to look at some data in another window to verify what you are seeing in the log, it is annoying that you need to find that specific line again

**Comment by pbek** [comment]
I will try to reproduce your issue.

**Comment by ghost** [comment]
I am running linux 

OS: Pop!_OS 19.10 x86_64
Kernel: 5.3.0-7648-generic
DE: GNOME 3.34.3

**Comment by pbek** [comment]
I can't reproduce that. The only time the cursor "moves to the top" for me is when the log file is reloaded (e.g. with `Ctrl + R`.

## General Info

**Version**: `18.11.3`
**Build date**: `Apr 21 2020`
**Operating System**: `KDE neon User Edition 5.18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Qt Version (build)**: `5.14.1`
**Qt Version (runtime)**: `5.14.1`
**Locale (interface)**: *empty*
**Icon theme**: *empty*

**Comment by ghost** [comment]
removed the program - reinstalled through snap and now it seems to be fixed

**Comment by pbek** [comment]
Ok, great. :laughing:
