### ISSUE TITLE
snap: Desktop file didn't specify Exec field

### ISSUE THREAD

**Issue by ghost** [pbek/loganalyzer#9]
Installed loganalyzer through the snap store and when I first wanted to run the program by clicking on the .desktop file in applications I got the error

Desktop file didn't specify Exec field

I manually fixed it but I don't know if this is a bug for you or is it purely a snap issue?

**Comment by pbek** [comment]
So does the desktop file on your computer have an `Exec` field?
The bundled https://github.com/pbek/loganalyzer/blob/15e43b687eacb11a6ce719383a01d15e9eadfd2c/snap/gui/LogAnalyzer.desktop should have one...

**Comment by ghost** [comment]
this was in the file

❯ cat loganalyzer-pbek_LogAnalyzer.desktop 

> [Desktop Entry]
> X-SnapInstanceName=loganalyzer-pbek
> Name=LogAnalyzer
> Comment=Tool for analyzing your log files by reducing the content with regular expression patterns you define
> Icon=LogAnalyzer
> Type=Application
> Terminal=false
> StartupNotify=true
> Categories=Qt;System;Monitor;

and i added 

> Exec=/snap/bin/loganalyzer-pbek

to fix it

**Comment by pbek** [comment]
Strange, my `/usr/share/applications/LogAnalyzer.desktop` had an `Exec` by itelself.

**Comment by pbek** [comment]
I can't say what went wrong on your computer.

**Comment by isamudaison** [comment]
Same issue with the snap. Not sure how to fix that case...

**Comment by pbek** [comment]
But you can run `loganalyzer-pbek` on the terminal, can't you?

**Comment by isamudaison** [comment]
It does execute form the terminal. Using ubuntu's launchpad search 'finds' the snap, but executing from that gives the error. I've added a desktop shortcut and that works better:
`nano ~/Desktop/LogAnalayzer.desktop`
write the following:
```
[Desktop Entry]
X-SnapInstanceName=loganalyzer-pbek
Name=LogAnalyzer
Comment=Tool for analyzing your log files by reducing the content with regular >
Icon=LogAnalyzer
Type=Application
Terminal=false
StartupNotify=true
Categories=Qt;System;Monitor;
Exec=/snap/bin/loganalyzer-pbek
```
On the desktop, you have to right-click and select `Allow launching` from the context menu.

I'm adding this here because generally UI apps in snap form I usually use the launchpad search to launch, and others might see the same issue.

**Comment by isamudaison** [comment]
Ok, I see now the embedded snap .desktop file is located here:
`/var/lib/snapd/desktop/applications`
One can simple `sudo nano loganalzyer-pbek_LogAnalyzer.desktop` from there to add the missing Exec line.

**Comment by pbek** [comment]
I just tried to fix the desktop file content and name in https://github.com/pbek/loganalyzer/commit/6b51c17b9d9309cf127e1d664559d93b97f98cf9. But I can't say much about it yet, because https://snapcraft.io/loganalyzer-pbek/builds gives me a gateway timeout.

**Comment by pbek** [comment]
I was able to manually trigger a build on snapcraft.io, when it's done you should be able to install a revision > 191 with `snap install loganalyzer-pbek --edge`.

**Comment by pbek** [comment]
The current snap (release and edge) should have a working desktop file. (it worked for me now)
Can you please test it and report back.

**Comment by isamudaison** [comment]
Can confirm; Looks & works great now, thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
